USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_CT_DONGHP]    Script Date: 12/6/2021 6:23:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE proc [dbo].[SP_CT_DONGHP]
@MASV nchar(10),
@NIENKHOA nchar(9),
@HOCKY INT
as begin
SELECT NGAYDONG, SOTIENDONG FROM CT_DONGHOCPHI 
WHERE MASV=@MASV AND NIENKHOA =@NIENKHOA AND HOCKY =@HOCKY;
end;

GO

