USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_DONGHP]    Script Date: 12/6/2021 6:24:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE proc [dbo].[SP_DONGHP]
@MASV nchar(10),
@NIENKHOA nchar(9),
@HOCKY INT,
@NGAYDONG DATE,
@SOTIENDONG INT
as begin
	IF EXISTS (SELECT * FROM CT_DONGHOCPHI WHERE MASV=@MASV AND NIENKHOA=@NIENKHOA AND  HOCKY=@HOCKY AND NGAYDONG=@NGAYDONG)
	RAISERROR ('Mỗi ngày chỉ lập 1 phiếu đóng học phí cho 1 một sinh viên, vui lòng kiểm tra lại!', 11, 1);
	ELSE 
	INSERT INTO CT_DONGHOCPHI(MASV, NIENKHOA, HOCKY, NGAYDONG,SOTIENDONG) VALUES (@MASV, @NIENKHOA,@HOCKY, @NGAYDONG, @SOTIENDONG); 
end;
GO

