USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_KTR_SV_LOP]    Script Date: 12/8/2021 10:31:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_KTR_SV_LOP] @MALOP		nChar(10),
	@NIENKHOA	nchar(9),
	@HOCKY		Int
as begin
select SVL.MASV, HO, TEN from	
				(select MASV, HO, TEN from SINHVIEN
				where MALOP=@MALOP AND DANGHIHOC ='FALSE') as SVL,
				(SELECT DISTINCT MASV FROM LINK0.QLDSV_TC.DBO.DANGKY AS DK,
						(SELECT MALTC FROM LINK0.QLDSV_TC.DBO.LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND HOCKY =@HOCKY AND HUYLOP = 'FALSE') AS LTC
				WHERE DK.MALTC =LTC.MALTC AND DK.HUYDANGKY ='FALSE') as SVDK
		where SVL.MASV =SVDK.MASV
END

GO

