USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_LAY_DSHP_LOP]    Script Date: 12/6/2021 6:32:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_LAY_DSHP_LOP] @MALOP		nChar(10),
	@NIENKHOA	nchar(9),
	@HOCKY		Int
as begin
	select SV.HO+' '+SV.TEN as HOTEN, ISNULL(HP.HOCPHI, 0) as HOCPHI, ISNULL(TIEN, 0) AS SOTIENDADONG
	from (select SVL.MASV, HO, TEN from	
				(select MASV, HO, TEN from SINHVIEN
				where MALOP=@MALOP AND DANGHIHOC ='FALSE') as SVL,
				(SELECT DISTINCT MASV FROM LINK0.QLDSV_TC.DBO.DANGKY AS DK,
						(SELECT MALTC FROM LINK0.QLDSV_TC.DBO.LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND HOCKY =@HOCKY AND HUYLOP = 'FALSE') AS LTC
				WHERE DK.MALTC =LTC.MALTC AND DK.HUYDANGKY ='FALSE') as SVDK
		where SVL.MASV =SVDK.MASV) as SV				
	left join (select MASV, HOCPHI from HOCPHI 
			where NIENKHOA=@NIENKHOA and HOCKY=@HOCKY) as HP
		on HP.MASV = SV.MASV
	left join (select MASV, SUM(SOTIENDONG) as TIEN from CT_DONGHOCPHI where NIENKHOA=@NIENKHOA and HOCKY=@HOCKY group by MASV) as CT
		on CT.MASV = HP.MASV
	
END;
GO

