USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [DBO].[SP_CAPNHAT_LTC]
	@NIENKHOA NCHAR(9),
	@HOCKY INT,
	@MALTC INT,
	@MAMH NCHAR(10),
	@NHOM INT,
	@MAGV NCHAR(10),
	@SOSVTOITHIEU SMALLINT,
	@HUY BIT,
	@SERVER_HIENTAI NCHAR(5),
	@SERVER_DICH NCHAR(5)
AS BEGIN
	BEGIN TRY
		IF(@SERVER_DICH = @SERVER_HIENTAI)
			UPDATE LOPTINCHI
			SET NIENKHOA = @NIENKHOA, HOCKY = @HOCKY, MAMH = @MAMH, NHOM = @NHOM, MAGV = @MAGV, SOSVTOITHIEU = @SOSVTOITHIEU, HUYLOP = @HUY
			WHERE MALTC = @MALTC
		ELSE 
			UPDATE [LINK1].[QLDSV_TC].[DBO].[LOPTINCHI]
			SET NIENKHOA = @NIENKHOA, HOCKY = @HOCKY, MAMH = @MAMH, NHOM = @NHOM, MAGV = @MAGV, SOSVTOITHIEU = @SOSVTOITHIEU, HUYLOP = @HUY
			WHERE MALTC = @MALTC
		

	END TRY

	BEGIN CATCH
		RAISERROR ('Định không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO