USE [QLDSV_TC]
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- LUU Y: PHAI CAP QUYEN CHO SV 
CREATE PROC [DBO].[SP_DS_DANGKY_LTC]
	@NIENKHOA NCHAR(9),
	@HOCKY INT,
	@MASV NCHAR(10)
AS BEGIN
	BEGIN TRY
		-- TAO BANG GANH TEN GIANG VIEN
		SELECT MALTC, MAMH, NHOM, HOTEN=G.HO+' '+G.TEN, NIENKHOA, HOCKY INTO #DS_CO_GV
		FROM LOPTINCHI L, GIANGVIEN G
		WHERE L.MAGV = G.MAGV AND L.HOCKY = @HOCKY AND L.NIENKHOA = @NIENKHOA AND L.HUYLOP = 0

		-- SELECT * FROM #DS_CO_GV

		-- TAO BANG TIM SO LUONG SINH VIEN DA DANG KY LTC
		SELECT COUNT(MASV) AS SSV, MALTC INTO #SLSV_THEO_LTC
		FROM DANGKY
		GROUP BY (MALTC)

		--SELECT * FROM #SLSV_THEO_LTC

		SELECT DS.*, ISNULL(SL.SSV, 0) AS SSV INTO #DS_CO_GV_SSV
		FROM #DS_CO_GV DS
		LEFT JOIN #SLSV_THEO_LTC SL
		ON DS.MALTC = SL.MALTC

		-- SELECT * FROM #DS_CO_GV_SSV

		-- KIEM TRA DA DANG KY MON HOC THEO MASV

		SELECT DS.*, CAST(ISNULL(DK.HUYDANGKY, 1) AS bit) AS CHUADANGKY INTO #DS_CO_GV_SSV_CHUADANGKY
		FROM #DS_CO_GV_SSV DS
		LEFT JOIN DANGKY DK
		ON DS.MALTC = DK.MALTC AND DK.MASV = @MASV

		SELECT * FROM #DS_CO_GV_SSV_CHUADANGKY

		-- THEM STT
		SELECT ROW_NUMBER() OVER(ORDER BY MALTC) AS STT, *
		FROM #DS_CO_GV_SSV_CHUADANGKY

	-- ROW_NUMBER() OVER(ORDER BY MAMH) AS STT,
	
	END TRY
	BEGIN CATCH
		RAISERROR ('Có lỗi xảy ra. Vui lòng kiểm tra lại', 11, 1);
	END CATCH
END
GO