USE [QLDSV_TC]
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [DBO].[SP_DS_LTC]
	@NIENKHOA NCHAR(9),
	@HOCKY INT,
	@MAMH NCHAR(10),
	@SERVER_HIENTAI NCHAR(5),
	@SERVER_DICH NCHAR(5)
AS BEGIN
	BEGIN TRY
	IF(@SERVER_HIENTAI = @SERVER_DICH)
		SELECT MALTC, MAKHOA, MAMH, MAGV, NIENKHOA, HOCKY, NHOM, SOSVTOITHIEU, HUYLOP FROM LOPTINCHI WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MAMH = @MAMH
	ELSE
		SELECT MALTC, MAKHOA, MAMH, MAGV, NIENKHOA, HOCKY, NHOM, SOSVTOITHIEU, HUYLOP FROM [LINK1].[QLDSV_TC].[DBO].[LOPTINCHI] WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MAMH = @MAMH
	END TRY
	BEGIN CATCH
		RAISERROR ('Có lỗi xảy ra. Vui lòng kiểm tra lại', 11, 1);
	END CATCH
END
GO