USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- DANH SACH SINH VIEN TRONG 1 LOP TIN CHI DUNG TRONG BAO CAO
CREATE PROC [DBO].[SP_DS_SV_1LTC_BAOCAO]
	@MALTC INT
AS BEGIN
	BEGIN TRY
		-- TAO DU LIEU CHUAN

		SELECT SV.MASV, HOTEN = SV.HO + ' ' + SV.TEN, SV.PHAI, SV.MALOP, SV.HO, SV.TEN INTO #DS_SV
		FROM SINHVIEN SV, DANGKY DK
		WHERE SV.MASV = DK.MASV AND DK.MALTC = @MALTC

		-- GAN STT VA CHINH NOI DUNG CAN
		SELECT ROW_NUMBER() OVER(ORDER BY TEN, HO) AS STT, MASV, HOTEN, PHAI, MALOP
		FROM #DS_SV
		
	END TRY

	BEGIN CATCH
		RAISERROR ('Định không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO