USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- DANH SACH LOP TIN CHI DUNG TRONG BAO CAO
CREATE PROC [DBO].[SP_DS_LTC_BAOCAO]
	@NIENKHOA NCHAR(9),
	@HOCKY INT
AS BEGIN
	BEGIN TRY
		-- TAO DU LIEU CHUAN
		SELECT * INTO #DS_CHUAN
		FROM LOPTINCHI WHERE HOCKY = @HOCKY AND NIENKHOA = @NIENKHOA AND HUYLOP = 0

		-- GAN TEN MON HOC
		SELECT DS.*, M.TENMH INTO #DS_CO_TENMON
		FROM #DS_CHUAN DS
		LEFT JOIN MONHOC M
		ON M.MAMH = DS.MAMH

		-- GAN TEN GIAO VIEN
		SELECT DS.*, HOTENGV = GV.HO+' '+GV.TEN INTO #DS_CO_TENMON_GV
		FROM #DS_CO_TENMON DS
		LEFT JOIN GIANGVIEN GV
		ON DS.MAGV = GV.MAGV


		-- DEM SO SV DK
		SELECT COUNT(MASV) AS SSV, MALTC INTO #SLSV_THEO_LTC
		FROM DANGKY
		GROUP BY (MALTC)

		--SELECT * FROM #SLSV_THEO_LTC

		SELECT DS.*, ISNULL(SL.SSV, 0) AS SSV INTO #DS_CO_TENMON_GV_SSV
		FROM #DS_CO_TENMON_GV DS
		LEFT JOIN #SLSV_THEO_LTC SL
		ON DS.MALTC = SL.MALTC

		-- GAN STT VA CHINH NOI DUNG CAN
		SELECT ROW_NUMBER() OVER(ORDER BY MALTC) AS STT, TENMH, NHOM, HOTENGV, SOSVTOITHIEU, SSV
		FROM #DS_CO_TENMON_GV_SSV
		
	END TRY

	BEGIN CATCH
		RAISERROR ('Định không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO