USE [QLDSV_TC]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
-- LẤY TÊN KHOA Ở PHÂN MẢNH HIỆN TẠI ÁP DỤNG CHO SERVER 1 VÀ SERVER 2
ALTER proc [dbo].[SP_LAY_TEN_KHOA_HIENTAI]
as begin
	select TENKHOA, MAKHOA from KHOA;
end
GO