USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- DANH SACH LOP TIN CHI DUNG TRONG BAO CAO
CREATE PROC [DBO].[SP_SLL_LTC_BAOCAO]
	@NIENKHOA NCHAR(9),
	@HOCKY INT
AS BEGIN
	BEGIN TRY
		-- TAO DU LIEU CHUAN
		SELECT COUNT(MALTC) AS SOLUONGLOP
		FROM LOPTINCHI WHERE HOCKY = @HOCKY AND NIENKHOA = @NIENKHOA AND HUYLOP = 0
		
	END TRY

	BEGIN CATCH
		RAISERROR ('Định không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO