USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- SO LUONG SINH VIEN TRONG 1 LOP TIN CHI DUNG TRONG BAO CAO
CREATE PROC [DBO].[SP_SLSV_1LTC_BAOCAO]
	@MALTC INT
AS BEGIN
	BEGIN TRY
		-- TAO DU LIEU CHUAN

		SELECT COUNT(MASV) AS SLSV
		FROM DANGKY
		WHERE MALTC = @MALTC
		
	END TRY

	BEGIN CATCH
		RAISERROR ('Định không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO