USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [DBO].[SP_THEM_LTC]
	@NIENKHOA NCHAR(9),
	@HOCKY INT,
	@MAMH NCHAR(10),
	@NHOM INT,
	@MAGV NCHAR(10),
	@SOSVTOITHIEU SMALLINT,
	@SERVER_HIENTAI NCHAR(5),
	@SERVER_THEM NCHAR(5)
AS BEGIN
	BEGIN TRY
		
		IF(EXISTS(SELECT MALTC FROM [LINK0].[QLDSV_TC].[DBO].[LOPTINCHI] WHERE NIENKHOA = @NIENKHOA AND HOCKY = @HOCKY AND MAMH = @MAMH AND NHOM = @NHOM))
			RAISERROR ('Thông tin bạn điền bị trùng. Vui lòng kiểm tra lại!', 11, 1);
		ELSE 
			IF(@SERVER_HIENTAI = @SERVER_THEM)
				INSERT INTO LOPTINCHI (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, SOSVTOITHIEU, MAKHOA) VALUES (@NIENKHOA, @HOCKY, @MAMH, @NHOM, @MAGV, @SOSVTOITHIEU, @SERVER_THEM)
			ELSE
				INSERT INTO [LINK1].[QLDSV_TC].[DBO].[LOPTINCHI] (NIENKHOA, HOCKY, MAMH, NHOM, MAGV, SOSVTOITHIEU, MAKHOA) VALUES (@NIENKHOA, @HOCKY, @MAMH, @NHOM, @MAGV, @SOSVTOITHIEU, @SERVER_THEM)

	END TRY

	BEGIN CATCH
		RAISERROR ('Định không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO