USE [QLDSV_TC]
GO

/****** Object:  StoredProcedure [dbo].[SP_XOALOGIN]    Script Date: 13/11/2021 4:11:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_XOALOGIN]
  @LGNAME VARCHAR(50),
  @USRNAME VARCHAR(50)
  
AS
  EXEC SP_DROPUSER @USRNAME
  EXEC SP_DROPLOGIN @LGNAME
GO


