USE [QLDSV_TC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [DBO].[SP_XOA_LTC]
	@MALTC INT,
	@SERVER_HIENTAI NCHAR(5),
	@SERVER_THEM NCHAR(5)
AS BEGIN
	BEGIN TRY
		
		IF(@SERVER_HIENTAI = @SERVER_THEM)
			DELETE FROM LOPTINCHI
			WHERE MALTC = @MALTC
		ELSE
			DELETE FROM [LINK1].[QLDSV_TC].[DBO].[LOPTINCHI]
			WHERE MALTC = @MALTC

	END TRY

	BEGIN CATCH
		RAISERROR ('Định dạng không đúng. Vui lòng kiểm tra lại!', 11, 1);
	END CATCH
END
GO